== Edit a Connected Azure Account

After you have added your Azure cloud account resources, you may from time to time want to review or update existing cloud resources or modify assigned permissions. Follow the steps below to view, edit or delete your Azure cloud account resources: 

*View an Added Account*

1. From the Prisma Cloud administrative console, navigate to *Settings > Cloud Accounts* to view a list of all your previously added cloud accounts. 

2. Locate the Azure account you wish to modify and click on the View icon. 

3. The *Status* tab lists the Account Details and provides a read out of the *Security Capabilities & Permissions* you have enabled. 

4. On the *Threat Detection* tab you can edit your flow log ingestion preferences. Select the *Edit* button and change your preferences in the *Configure Account* page of the onboarding workflow.

5. The *Workload Security* allows you to add or delete Compute security capabilities and permissions. Click the *Enable* or *Disable* toggle to change your selections. You can also select the *Edit* button at the top of the page and navigate to the *Get Started* onboarding workflow to change your preferences. 

6. If a Security capability displays an *Issues Found* flag. You can click on the link to view a quick summary of the issue and available remediation options.

*Edit an Added Account*

1. On the *Cloud Accounts* page you can also edit the existing *Security Capabilities & Permissions* of already added accounts. 

2. Locate the Azure account you wish to modify and click on the Edit icon. 

3. The *Edit Cloud Account* page allows you to add or change *Security Capabilities & Permissions*. You can also opt in or out of ingesting flow logs. Reference the Connect Prisma Cloud Account page for more information.  