:topic_type: task
[.task]
[#idd4a9fb0b-59df-473b-8547-789be4c18ec5]
== Update Azure Application Permissions

Even after you have completed onboarding, you have the option to add or remove Prisma Cloud Security Capabilities.

This workflow outlines how you can add additional capabilities and the required associated permissions in your Azure subscriptions or tenants post onboarding. To verify if you have missing permissions authenticate into Prisma Cloud and select menu:Settings[Cloud Accounts], and view the *Status* column.

=== Update Azure Custom Role Permissions

When adding new Security Capabilities, you will first need to update the permissions granted to the existing custom role created during the onboarding process. This workflow is only available if you used the Azure Tenant or Subscription onboarding workflow. 

==== Using Terraform Script (Recommended)

Follow the steps below to update your custom role permissions and add or modify existing Prisma Cloud Security Capabilities.

[NOTE]
====
 Azure China workflows does not support the use of Terraform templates.
====

. Authenticate with Azure CLI. 

. Navigate to the directory you created during the onboarding process to store the Terraform file. Sample directory names include, [userinput] onboard-tenant-<tenant-name> or [userinput] onboard–subscription-<subscription-name>. Ensure that the directory contains the [userinput] terraform.tfstate file created during the *terraform apply step*. 

. Select the required features under Security Capabilities and Permissions section in the Get Started dialog.

. Download the Terraform again by clicking on *Edit Cloud Account > Configure Account > Download Terraform Script* button. The newly downloaded Terraform file contains the updated permissions.

. Run the command *terraform init > terraform apply* and click *Confirm*.

. The existing custom role is now updated with new permissions, once the Terraform execution is completed.


[NOTE]
====
If the terraform.tfstate file is not present in the directory, when the terraform script is executed, a new app is registered and a new custom roles is created.
====

==== Manually update Custom Roles 

		 	 	 		
If your organization restricts the use of Terraform scripts, you can choose to manually add the new permissions to the existing custom roles. 

. Authenticate into https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-your-azure-account/update-azure-application-permissions[Azure portal]. 

. For Tenant Workflow: Navigate to *All Services > Management Groups*. Click on Tenant Root Group 
  For Subscription Workflow: Navigate to *All Services > Subscriptions*.
	
. Select Access Control (IAM) > Roles.
	
. Search for the custom role created during onboarding in the *Search* box and click on the *Edit* button.

. Update the custom role page, click on JSON. You can view your existing custom role JSON with the permissions under the actions list.

. Click on the *Edit* button, append the comma separated new permissions in the actions list. Click on *Save > Review + update*.

. Verify your *Role name and Permissions*. Click on *Update*. Wait for few minutes for the custom role to update.


+++<draft-comment>The conref is located here: //depot/tech-pubs/documentation/en_US/prisma/prisma-cloud/prisma-cloud-admin-guide/register-an-app-on-azure-active-directory.xml</draft-comment>+++


[.procedure]
. Authenticate into https://portal.azure.com[Azure portal].

include::../../fragments/ida0e4567f-7cf3-455b-b755-b2e2072ae0a0__idfd28e1a8-113d-480e-a1a0-5c235bbee0e9.adoc[]

include::../../fragments/ida0e4567f-7cf3-455b-b755-b2e2072ae0a0__ide5f1bbad-c2c6-493a-a5c3-c01fe0fc7390.adoc[]
